spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.routes[0].id=admin-products-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.routes[1].id=public-products-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/public/**

management.endpoints.web.exposure.include=health,info