version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: sanarte_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "9090:80"
    depends_on:
      - postgres
    networks:
      - backend-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - admin-products-service
      - public-products-service
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: admin-products-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://admin-products-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/admin/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: public-products-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://public-products-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/api/public/**
    networks:
      - backend-network

  admin-products-service:
    build: ./admin-products-service
    container_name: admin-products-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sanarte_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - backend-network

  public-products-service:
    build: ./public-products-service
    container_name: public-products-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sanarte_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge