spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.routes[0].id=admin-products-service
spring.cloud.gateway.routes[0].uri=${ADMIN_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.routes[1].id=public-products-service
spring.cloud.gateway.routes[1].uri=${PUBLIC_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/public/**

management.server.port=8090
management.endpoints.web.exposure.include=health,info